apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
spec:
  backend:
    serviceName: argo-ui
    servicePort: 80
  tls:
  - hosts:
    - argo.masarik.sh
    secretName: testsecret-tls
