apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-event-source
  labels:
    argo-events-event-source-version: v0.10
data:
  foo: |-
    port: "12000"
    endpoint: "/secret-webhook-endpoint"
    method: "POST"