apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    argo-events-sensor-version: v0.10
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  dependencies:
    - name: "webhook-gateway:foo"
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  triggers:
    - template:
        name: webhook-workflow-trigger
        group: argoproj.io
        version: v1alpha1
        kind: Workflow
        source:
          s3:
            bucket:
              name: workflowconfigs
              key: KEY
            endpoint: storage.googleapis.com
            accessKey:
              key: accessKey
              name: minio-secrets
            secretKey:
              key: secretKey
              name: minio-secrets
      resourceParameters:
        - src:
            event: "webhook-gateway:foo"
            path: domain
          dest: spec.arguments.parameters.0.value
        - src:
            event: "webhook-gateway:foo"
            path: company
          dest: spec.arguments.parameters.1.value
        - src:
            event: "webhook-gateway:foo"
            path: chain
          dest: spec.arguments.parameters.2.value
      templateParameters:
        - src:
            event: "webhook-gateway:foo"
            path: workflow
          dest: source.s3.bucket.key
