apiVersion: argoproj.io/v1alpha1
kind: Workflow

metadata:
  generateName: gitsecrets-

spec:
  entrypoint: entrypoint

  arguments:
    parameters:
      - name: domain
        value:
      - name: company
        value:
      - name: git-name
        value: "[]"
      - name: git-type
        value: "[]"
      - name: chain
        value: "[]"

  volumes:
    - name: my-secret-vol
      secret:
        secretName: gitlab-ssh
    - name: config
      secret:
        secretName: configs

  templates:
    - name: entrypoint
      steps:
        - - name: gitleaks
            template: gitleaks
            arguments:
              parameters:
                - name: name
                  value: "{{workflow.parameters.git-name}}"
                - name: switch
                  value: "--{{workflow.parameters.git-type}}-org"
        - - name: push-results
            template: push-results
            arguments:
              artifacts:
                - name: gitleaks
                  from: "{{steps.gitleaks.outputs.artifacts.results}}"

    - name: gitleaks
      inputs:
        parameters:
          - name: switch
          - name: name
      container:
        image: s14ve/gitleaks:2.0
        resources:
          requests:
            memory: 700Mi
          limits:
            memory: 3Gi
        volumeMounts:
          - name: config
            mountPath: "/config"
        command: [sh, -c]
        args: ["/usr/bin/gitleaks --disk --report=/tmp/gitleaks.csv --config=/config/gitleaks.toml {{inputs.parameters.switch}}={{inputs.parameters.name}} || true"]
      outputs:
        artifacts:
          - name: results
            path: /tmp/gitleaks.csv

    - name: push-results
      retryStrategy:
        limit: 3
      inputs:
        artifacts:
          - name: gitleaks
            path: /tmp/gitleaks.csv
          - name: targetdata
            path: /targetdata
            git:
              repo: git@gitlab.com:janmasarik/targetdata.git
              revision: master
              sshPrivateKeySecret:
                name: gitlab-ssh
                key: ssh-private-key
      script:
        image: alpine/git:1.0.4
        command: [sh]
        source: |
          cd /targetdata
          git pull
          mkdir "/targetdata/{{workflow.parameters.domain}}"

          cp /tmp/gitleaks.csv "/targetdata/{{workflow.parameters.domain}}/gitleaks.{{workflow.parameters.git-name}}.{{workflow.parameters.git-type}}.csv"

          cp /secret/ssh-private-key /ssh-private
          chmod 400 /ssh-private
          git config --global user.email "gitleaks@argo.com"
          git config --global user.name "{{workflow.name}}"
          git add *
          git commit -m "{{workflow.name}} | {{workflow.parameters.domain}}"
          GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -i /ssh-private' git push
        volumeMounts:
          - name: my-secret-vol
            mountPath: "/secret"
